### ISSUE TITLE
Move `sledgehammer::element` and `sledgehammer::attribute` modules into this crate

### ISSUE THREAD

**Issue by StratusFearMe21** [ealmloff/sledgehammer_utils#1]
Given that the `sledgehammer` crate has been archived, it would be a shame to lose the large and quite useful `Element` and `Attribute` types provided by that crate. Seems like this would be the best crate to move those types to

**Comment by StratusFearMe21** [comment]
I would open a PR for this, but given that these types depended on `sledgehammer`'s dom-oriented messaging protocol to function, it would be necessary to make these types agnostic to that. Unfortunately I'm not knowledgeable enough of this crate or JavaScript in general to make that happen and for it to be up to performance standards

**Comment by ealmloff** [comment]
I agree that could be worth preserving in some way. It is one optimization I never ended up porting to the sledgehammer-bindgen crate but it could be useful for some cases. I did add a example illustrating how that optimization would work with sledgehammer-bindgen [here](https://github.com/Demonthos/sledgehammer_bindgen/blob/master/examples/typed_elements.rs)

I don't think the Element and Attribute types fit very well in this repo. Every crate that uses sledgehammer need the current utilities even if they do not run in a DOM environment.

It could be interesting to build a crate like sledgehammer with DOM focused utilities over sledgehammer-bindgen in the future, but it isn't something I am interested in right now. My main concern is the messages you define for sledehammer-bindgen are very important for performance and I'm not convinced that a version that is generalized for every framework makes sense. If you are already giving up a lot of ergonomics for better performance by choosing sledgehammer over web-sys it seems logical to define a custom set of instructions that is tuned for performance in your use case especially because you cannot easily share date between two bindings

I tried to use the generalized sledgehammer types initially with [dioxus](https://github.com/DioxusLabs/dioxus/), but they were too limiting, so I ended up writing a new set of bindings. One solution to this problem would be to create a nicer layer that could allow multiple sets of bindings to pass objects back and forth (like wasm-bindgen types) so that you could combine the element type with custom bindings
